version: '3.8'          # space after colon

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:8000