name: Train-Register-Deploy

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'configs/**' ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }

      - name: Install & set path
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Train model
        run: python -m src.train
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}